![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
impares = my_array[my_array % 2 != 0]
print(impares[::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [12]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [20]:
my_array[0:3][::-1]

array([2, 1, 0])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [40]:
matriz = np.arange(20).reshape((4,5))
matriz

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
matriz_invertida = matriz[::-1, ::-1]
matriz_invertida

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [42]:
ejercicio5 = matriz[0:2, 1:3]
ejercicio5

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [43]:
matriz.reshape(2,10)[::, 1:7:2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [49]:
matriz_fila = matriz.reshape(1,-1)

In [54]:
matriz_fila[::,1:16].reshape(3,-1)[::,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [56]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [59]:
loros = x[x == "Loro"]
print(loros)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [60]:
secuencia = np.arange(20)

In [63]:
secuencia.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [65]:
ceros = np.zeros(10)

In [66]:
ceros.nbytes

80

In [68]:
ceros[4] = 1
ceros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [72]:
vector = np.arange(10,50)[::-1]
vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [74]:
vector12 = np.array([1,2,0,0,4,0])

In [78]:
indices = np.nonzero(vector12)
indices

(array([0, 1, 4]),)

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
aleatorios = np.random.rand(10,10)
aleatorios

TypeError: type numpy.ndarray doesn't define __round__ method

In [89]:
print('Mínimo = ', aleatorios.min())
print('Máximo = ', aleatorios.max())

Mínimo =  0.0186277092204723
Máximo =  0.9999959798624001


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [91]:
vector = np.arange(30)

In [92]:
vector.mean()

np.float64(14.5)

## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [111]:
cuadrado = np.zeros((4,4))

In [112]:
def bordes_unos_centros_cero(cuadrado):
    for i in range(len(cuadrado)):
        for j in range(len(cuadrado)):
            if i in [0,len(cuadrado)-1] or j in [0,len(cuadrado)-1]:
                cuadrado[i][j] = 1
            else:
                cuadrado[i][j] = 0

    return cuadrado

In [113]:
bordes_unos_centros_cero(cuadrado)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [135]:
fila1 = np.zeros((1,7))
for i in range(fila1.shape[1]):         #crea el patron de la primera fila
    if i % 2 != 0:
        fila1[0, i] = 1
    else:
        fila1[0, i] = 0
print(fila1)

fila2 = np.zeros((1,7))             # crea el patron de la segunda fila
for i in range(fila2.shape[1]):
    if i % 2 == 0:
        fila2[0, i] = 1
    else:
        fila2[0, i] = 0
print(fila2)

print()
matriz_2filas= np.vstack((fila1,fila2))
matriz_ej16 = np.vstack((matriz, matriz, matriz))
matriz_ej16


[[0. 1. 0. 1. 0. 1. 0.]]
[[1. 0. 1. 0. 1. 0. 1.]]



array([[0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])

array([[0., 0., 0., 0., 0., 0., 0.]])

## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [147]:
fila1 = np.tile([0,1],3)        # Creamos el patron de la primera fila
fila1 = np.append(fila1,0)

fila2 = np.tile([1,0], 3)       # Creamos el patrón de la segunda fila
fila2 = np.append(fila2, 1)

filas1_2 = np.vstack((fila1, fila2))        #las juntamos
filas1_2

matriz = np.tile(filas1_2, (3,1))       # apilamos 3 veces
matriz

array([[0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [149]:
matriz = np.random.randint(1,20,(5,5))
matriz

array([[ 9, 11, 11, 13,  8],
       [ 4, 11, 15,  5, 18],
       [ 5,  3, 18,  2,  3],
       [12,  4, 15,  8, 15],
       [ 8,  3,  2, 10, 14]])

In [155]:
matriz_normalizada = np.zeros((5,5))
for i in range(matriz.shape[0]):
    for j in range(matriz.shape[1]):
        matriz_normalizada[i, j] = ((matriz[i, j] - np.mean(matriz)) / np.std(matriz))
print(matriz_normalizada)

[[-0.01601487  0.38435685  0.38435685  0.78472857 -0.21620073]
 [-1.01694416  0.38435685  1.18510028 -0.8167583   1.78565786]
 [-0.8167583  -1.21713002  1.78565786 -1.41731588 -1.21713002]
 [ 0.58454271 -1.01694416  1.18510028 -0.21620073  1.18510028]
 [-0.21620073 -1.21713002 -1.41731588  0.18417099  0.98491443]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [161]:
seq = np.arange(11)

In [164]:
seq2 = np.where((seq>=3) & (seq <=8), -1, seq)
seq2

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [165]:
seq2 = np.where((seq>=3) & (seq <=8), False, seq)
seq2

array([ 0,  1,  2,  0,  0,  0,  0,  0,  0,  9, 10])